---
title: "Raster Vector Exercise"
author: "Loïc Dutrieux"
date: "Tuesday, January 13, 2015"
output: slidy_presentation
---

# Solution

[https://github.com/GeoScripting-WUR/exerciseLesson6](https://github.com/GeoScripting-WUR/exerciseLesson6)

---

Use of extract.

```{r, eval=FALSE}
?extract
## S4 method for signature 'Raster,SpatialPolygons'
extract(x, y, fun=NULL, na.rm=FALSE, weights=FALSE, cellnumbers=FALSE,
     small=TRUE, df=FALSE, layer, nl, factors=FALSE, sp=FALSE, ...)
```

`sp = TRUE` will return the initial SPDF, with the extracted values appended to the `@data` slot.

* No need to run for each feature independently
* Also you can extract all layers of the raster brick at once
* Watch out for NAs

```{r}
a <- c(1,2,3,4,5,NA)
a
mean(a)
mean(a, na.rm = TRUE)
```

---

# Subset to identify the greenest city

```{r, eval=FALSE}
# Find out the greenest city in January
maxJanuarySPDF <- green[green$January == max(green$January),]
maxAugustSPDF <- green[green$August == max(green$August),]

# Or using subset() on the dataframe only
greenDf <- green@data
# The subset= argument selects rows; the select= argument selects columns
subset(greenDf, subset = January == max(greenDf$January), select = c(NAME_2, January))
subset(greenDf, subset = August == max(greenDf$August), select = c(NAME_2, August))
```

Subset():

* Only works on dataframes (spdf@data)
* `subset =` selects row
* `select =` selects columns



